name: Transform arXiv Categories

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  transform-categories:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install loguru
    
    - name: Run transformation script
      run: python transform_categories.py
